from enum import Enum

class TipoMensagem(str, Enum):
    ENTRAR_FILA = 'ENTRAR_FILA'
    SAIR_FILA = 'SAIR_FILA'
    FILA_ATUALIZADA = 'FILA_ATUALIZADA'
    PARTIDA_ENCONTRADA = 'PARTIDA_ENCONTRADA'
    ACEITAR_PARTIDA = 'ACEITAR_PARTIDA'
    RECUSAR_PARTIDA = 'RECUSAR_PARTIDA'
    PARTIDA_CANCELADA = 'PARTIDA_CANCELADA'
    PARTIDA_INICIADA = 'PARTIDA_INICIADA'
    ENVIAR_FROTA = 'ENVIAR_FROTA'
    FROTAS_CONFIRMADAS = 'FROTAS_CONFIRMADAS'
    DISPARAR_TIRO = 'DISPARAR_TIRO'
    RESULTADO_TIRO = 'RESULTADO_TIRO'
    OPONENTE_DESCONECTOU = 'OPONENTE_DESCONECTOU'
    FIM_PARTIDA = 'FIM_PARTIDA'
    ERRO = 'ERRO'
